[server]
headless = true

[ui]
hideTopBar = false

[global]
showWarningOnDirectExecution = false

[runner]
magicEnabled = false
installTracer = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server.fileWatcherType]
watcherType = "auto"

[server.runOnSave]
runOnSave = true

[app]
# ðŸ‘‡ This tells Streamlit which file to run
main = "app/streamlit_app.py"
